language: go
go:
  - 1.9
install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo/ginkgo
before_script:
script:
  - glide install
  - go build .
  - ginkgo -p -skipMeasurements -v $(glide novendor)
